CREATE TABLE appointments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_name VARCHAR(255)                            NOT NULL,
    client_name  VARCHAR(255)                            NOT NULL,
    date_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    duration     BIGINT                                  NOT NULL,
    price        DECIMAL(12, 2)                          NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);